actors:
  - echo
  - time

broker: "amqp://python:1234@rabbit/nameko"
rpc_timeout: 5.0
serializer: "datetimejson"
nameko:
  connection_timeout: 2.0

event_listener:
  heartbeat: null

broker: "amqp://python:Yatezu7egeStuc3fadaM@serv.home.lan/nameko"
rpc_timeout: 5.0
serializer: "datetimejson"
nameko:
  connection_timeout: 2.0

event_listener:
  heartbeat: null


actors:
  - ping
  - time


LOGGING:
  version: 1
  formatters:
    simple:
      format: "%(levelname)s %(message)s"
    verbose:
      format: "%(asctime)s %(levelname)-8s [%(name)s%(function)s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    colored:
      "()": "colorlog.ColoredFormatter"
      format:
        "%(blue,bold)s%(asctime)s%(reset)s %(log_color)s%(levelname)-8s%(reset)s%(blue)s[%(name)s%(function)s]%(reset)s %(message_log_color)s%(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
      log_colors:
        DEBUG: "cyan"
        INFO: "green"
        WARNING: "white,bg_yellow"
        ERROR: "yellow,bg_red"
        CRITICAL: "yellow,bg_red"
      secondary_log_colors:
        message:
            DEBUG: "cyan"
            INFO: "green"
            WARNING: "yellow"
            ERROR: "red"
            CRITICAL: "red,bg_white"
  filters:
    my:
      "()": "flotils.logable.FunctionFilter"
  handlers:
    null:
      level: INFO
      class: "logging.NullHandler"
      filters: ["my"]
    console:
      level: DEBUG
      formatter: colored
      class: logging.StreamHandler
      filters: ["my"]
  loggers:
    "":
      handlers: [console]
      propagate: True
      level: DEBUG
    amqp:
      level: DEBUG
    nameko:
      level: DEBUG
