version: "3"
services:

################
# Broker
################
  rabbit:
    image: rabbit-img:latest
    container_name: rabbit
    build: ./rabbit
    restart: always
    ports:
      - "15672:15672"

################
# Managers
################
  manager_intent:
    image: alex-manager-intent-img:latest
    container_name: alex-im
    build: ./intent_manager
    restart: always
    links:
      - rabbit
    depends_on:
      - rabbit
      - intent_direct

  manager_actor:
    image: alex-manager-actor-img:latest
    container_name: alex-am
    build: ./actor_manager
    restart: always
    links:
      - rabbit
    depends_on:
      - rabbit

################
# Actors
################

  actor_echo:
    image: alex-actor-echo-img:latest
    container_name: alex-a-echo
    build: ./actors/echo
    restart: always
    links:
      - rabbit
    depends_on:
      - rabbit
      - manager_actor


################
# Communicators
################

  communicator_hello:
    image: alex-communicator-hello-img:latest
    container_name: alex-c-hello
    build: ./communicators/hello
    restart: always
    links:
      - rabbit
    depends_on:
      - rabbit
      - manager_intent


################
# Intents
################

  intent_direct:
    image: alex-intent-direct-img:latest
    container_name: alex-i-direct
    build: ./intents/direct
    restart: always
    links:
      - rabbit
    depends_on:
      - rabbit
